apiVersion: "v1"
kind: "Service"
metadata:
  name: "napg-app-lb"
  labels:
   app: "nagp-app-lb"
spec:
   ports:
      - protocol: TCP
        port: 80
        targetPort: 8081  
   selector:
        app: devops-app
   type: "LoadBalancer"          